name: image_processors

services:
  mongo_instance:
    container_name: mongo_instance
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB_DATABASE}
    ports:
      - ${MONGO_DB_PORT}:${MONGO_DB_PORT}
